# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms\pdfcompdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pdfcompress(object):
    def setupUi(self, pdfcompress):
        pdfcompress.setObjectName("pdfcompress")
        pdfcompress.resize(761, 273)
        pdfcompress.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayout = QtWidgets.QVBoxLayout(pdfcompress)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(pdfcompress)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 741, 69))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayoutFilesList = QtWidgets.QVBoxLayout()
        self.verticalLayoutFilesList.setObjectName("verticalLayoutFilesList")
        self.verticalLayout_2.addLayout(self.verticalLayoutFilesList)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_4 = QtWidgets.QLabel(pdfcompress)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.progressBar = QtWidgets.QProgressBar(pdfcompress)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.checkBoxFileName = QtWidgets.QCheckBox(pdfcompress)
        self.checkBoxFileName.setObjectName("checkBoxFileName")
        self.horizontalLayout_2.addWidget(self.checkBoxFileName)
        self.label = QtWidgets.QLabel(pdfcompress)
        self.label.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.spinBoxCompression = QtWidgets.QSpinBox(pdfcompress)
        self.spinBoxCompression.setSpecialValueText("")
        self.spinBoxCompression.setMaximum(4)
        self.spinBoxCompression.setProperty("value", 2)
        self.spinBoxCompression.setObjectName("spinBoxCompression")
        self.horizontalLayout_2.addWidget(self.spinBoxCompression)
        self.pushButtonAction = QtWidgets.QPushButton(pdfcompress)
        self.pushButtonAction.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.pushButtonAction.setObjectName("pushButtonAction")
        self.horizontalLayout_2.addWidget(self.pushButtonAction)
        self.pushButtonCancel = QtWidgets.QPushButton(pdfcompress)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout_2.addWidget(self.pushButtonCancel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(pdfcompress)
        QtCore.QMetaObject.connectSlotsByName(pdfcompress)

    def retranslateUi(self, pdfcompress):
        _translate = QtCore.QCoreApplication.translate
        pdfcompress.setWindowTitle(_translate("pdfcompress", "List of files to compress:"))
        self.label_4.setText(_translate("pdfcompress", "Progress:"))
        self.checkBoxFileName.setText(_translate("pdfcompress", "Auto file names"))
        self.label.setText(_translate("pdfcompress", "Compression level:"))
        self.pushButtonAction.setText(_translate("pdfcompress", "Compress"))
        self.pushButtonCancel.setText(_translate("pdfcompress", "Cancel"))
